# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Инструктор', 'verbose_name_plural': 'Инструкторы'},
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
    ]
