# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20180920_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='age',
            field=models.IntegerField(default=1, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='car',
            field=models.CharField(default=1, max_length=20, verbose_name='Автомобиль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='category',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default=1, max_length=20, verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='city',
            field=models.CharField(choices=[('tymen', 'Тюмень')], default=1, max_length=20, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='driving_experience',
            field=models.IntegerField(default=1, verbose_name='Стаж вождения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='experience',
            field=models.IntegerField(default=1, verbose_name='Проф. стаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='gender',
            field=models.CharField(choices=[('men', 'Мужской'), ('women', 'Женский')], default=1, max_length=20, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='length_of_hour',
            field=models.IntegerField(choices=[('45', '45'), ('60', '60')], default=1, verbose_name='Продолжительность часа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='patronymic',
            field=models.CharField(default=1, max_length=20, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='price_hour',
            field=models.IntegerField(default=1, verbose_name='Стоимость часа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='school',
            field=models.CharField(choices=[('formula', 'ФОРМУЛА')], default=1, max_length=20, verbose_name='Автошкола'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='surname',
            field=models.CharField(default=1, max_length=20, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='transmission',
            field=models.CharField(choices=[('mkpp', 'Мкпп'), ('akpp', 'Акпп')], default=1, max_length=20, verbose_name='Коробка передач'),
            preserve_default=False,
        ),
    ]
