# Generated by Django 2.1.1 on 2018-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_auto_20180920_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
    ]
